# Generated by Django 3.2.12 on 2024-06-29 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登録日時'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todolist',
            name='duedate',
            field=models.DateField(verbose_name='〆切'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='memo',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
