# Generated by Django 3.2.12 on 2024-07-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todostatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todolist.todostatus', verbose_name='処理状況'),
            preserve_default=False,
        ),
    ]
